replay_folder: "C:\\Users\\manuel\\OneDrive\\Documents\\StarCraft II\\Accounts\\250568\\2-S2-1-691545\\Replays\\Multiplayer"
instant_leave_max: 60
deamon_polling_rate: 10

microphone_index: 2

student: "zatic"

gpt_model: "gpt-3.5-turbo"

open_ai_model: "gpt-4-1106-preview"

recognizer:
  # minimum audio energy to consider for recording
  energy_threshold: 400
  # seconds of non-speaking audio before a phrase is considered complete
  pause_threshold: 0.5

  # minimum seconds of speaking audio before we consider the speaking audio a phrase - values below this are ignored (for filtering out clicks and pops)
  phrase_threshold: 0.3
  # seconds of non-speaking audio to keep on both sides of the recording
  non_speaking_duration: 0.2

ladder_maps:
  - "babylon le"
  - "dragon scales le"
  - "neohumanity le"
  - "royal blood le"
  - "altitude le"
  - "ancient cistern le"
  - "gresvan le"
