name: "AICoach"
replay_folder: "C:\\Users\\manuel\\OneDrive\\Documents\\StarCraft II\\Accounts\\250568\\2-S2-1-691545\\Replays\\Multiplayer"
instant_leave_max: 60
deamon_polling_rate: 10

microphone_index: 2

oww_model: "hey_jarvis"

student: "zatic"

gpt_model: "gpt-4-1106-preview"

speech_recognition_model: "openai/whisper-large-v3"

screenshot: "obs/screenshots/_maploading.png"

recognizer:
  # minimum audio energy to consider for recording
  energy_threshold: 400
  # seconds of non-speaking audio before a phrase is considered complete
  pause_threshold: 0.5

  # minimum seconds of speaking audio before we consider the speaking audio a phrase - values below this are ignored (for filtering out clicks and pops)
  phrase_threshold: 0.3
  # seconds of non-speaking audio to keep on both sides of the recording
  non_speaking_duration: 0.2

season: 57

ladder_maps:
  - hecate le
  - oceanborn le
  - solaris le
  - hard lead le
  - radhuset station le
  - site delta le
  - equilibrium le
  - goldenaura le
  - alcyone le
