name: "AICoach"
# Where to look for replays
replay_folder: "C:\\Users\\student\\Documents\\StarCraft II\\Accounts\\1234567568\\2-S2-1-123456\\Replays\\Multiplayer"
# Game shorter than this will be ignored and the replays deleted
instant_leave_max: 50
# Look for new replays every X seconds
deamon_polling_rate: 1

# Audiomode, one of "fullaudio", "text", "in", "out"
audiomode: "text"
# Index of the audio device as returned by pyaudio
microphone_index: 2
# Which model to use from openwakeword
oww_model: "hey_jarvis"
# Sensitivity of the wake word
oww_sensitivity: 0.7
# which speech recognition model to use from huggingface speech-to-text
speech_recognition_model: "openai/whisper-large-v3"
# Configure speech recognition from microphone
recognizer:
  # minimum audio energy to consider for recording
  energy_threshold: 400
  # seconds of non-speaking audio before a phrase is considered complete
  pause_threshold: 0.5
  # minimum seconds of speaking audio before we consider the speaking audio a phrase - values below this are ignored (for filtering out clicks and pops)
  phrase_threshold: 0.3
  # seconds of non-speaking audio to keep on both sides of the recording
  non_speaking_duration: 0.2
# Hotkey to call up the AI coach prompt when run in text-in mode
wake_key: "ctrl+alt+w"

# Configure the "student" - the player using AI coach
student:
  name: "studentname"
  race: "Zerg"
  # Emoji to represent the student in output
  emoji: ":man_technologist:"
  # URL pointing to your public sc2replaystats profile's map stats
  sc2replaystats_map_url: "https://sc2replaystats.com/account/maps/12345/0/1234567/1v1/AutoMM"

# Integration with OBS; Faster detection of new game started but requires manual OBS setup
obs_integration: False
# which GPT model to use for OpenAI Assistant API
gpt_model: "gpt-4-turbo"
# relative path to screenshot file which OBS takes when the map is loading
screenshot: "obs/screenshots/_maploading.png"
# Where tesserocr should look for the tesseract data
tessdata_dir: "C:\\Program Files\\Tesseract-OCR\\tessdata"
# Current ladder season
season: 59
# Maps in the current ladder pool
ladder_maps:
  - Goldenaura LE
  - Site Delta LE
  - Oceanborn LE
  - Post-Youth LE
  - Amphion LE
  - Crimson Court LE
  - Dynasty LE
  - Alcyone LE
  - Ghost River LE
# Configure which replay fields to include per default when reading replays
default_projection:
  _id: 1
  date: 1
  game_length: 1
  map_name: 1
  players.avg_apm: 1
  players.highest_league: 1
  players.name: 1
  players.messages: 1
  players.pick_race: 1
  players.pid: 1
  players.play_race: 1
  players.result: 1
  players.scaled_rating: 1
  players.stats: 1
  players.toon_handle: 1
  players.build_order.time: 1
  players.build_order.name: 1
  players.build_order.supply: 1
  players.build_order.is_chronoboosted: 1
  real_length: 1
  stats: 1
  unix_timestamp: 1
# Name of the MongoDB database where the replay collection is stored
db_name: "SC2"
