channels:
  - conda-forge
  - huggingface
dependencies:
  - python=3.10
  - requests
  - python-dotenv
  - click
  - pyyaml
  - pymongo
  - numpy
  - pandas
  - openai
  - pytest
  - tiktoken
  - rich
  - pytesseract
  - beautifulsoup4
  - python-levenshtein
  - onnxruntime
  - blinker
  - pytorch
  - pysoundfile
  - pip
  - pip:
      - pyaudio
      - opencv-python
      - sc2reader
      - spawningtool
      - openwakeword
      - optimum
      - accelerate
      - transformers
      - SpeechRecognition
      - pyttsx3
