name: aicoach311-minimal
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pydantic
  - pydantic-settings
  - pyyaml
  - httpx
  - click
  - pymongo
  - openai
  - tiktoken
  - rich
  - python-levenshtein
  - jinja2
  - pandas
  - pip
  - pip:
      - git+https://github.com/NumberPigeon/sc2reader-plugins.git
      - git+https://github.com/StoicLoofah/spawningtool.git@master
      - pyodmongo
      - keyboard
      - climage
      - blizzardapi2