name: aicoach311-ci
channels:
  - conda-forge
dependencies:
  - python=3.11
  - conda-forge::pydantic=2.6
  - conda-forge::pydantic-settings
  - pyyaml
  - conda-forge::httpx
  - click
  - conda-forge::openai
  - pytest
  - pytest-mock
  - pytest-cov
  - python-levenshtein
  - blinker
  - jinja2
  - pip
  - pip:
      - opencv-python
      - sc2reader
      - spawningtool
      - pyodmongo
      - keyboard
      - blizzardapi2
      - git+https://github.com/NumberPigeon/sc2reader-plugins.git
