name: aicoach311
channels:
  - conda-forge
  - huggingface
dependencies:
  - python=3.11
  - pydantic
  - pydantic-settings
  - pyyaml
  - pandas
  - tabulate
  - httpx
  - click
  - numpy
  - openai
  - pytest
  - pytest-mock
  - pytest-cov  
  - tiktoken
  - rich
  - simonflueckiger::tesserocr
  - beautifulsoup4
  - python-levenshtein
  #- pytorch # conda install pytorch torchvision torchaudio pytorch-cuda=12.1 -c pytorch -c nvidia
  - jupyter
  - matplotlib
  - webrtcvad
  - scipy
  - jinja2
  - pillow
  - pip
  - pip:
      - pyaudio
      - pysoundfile
      - opencv-python
      - openwakeword
      - onnxruntime-gpu
      - accelerate
      - transformers
      - SpeechRecognition
      #- flash_attn # https://pypi.org/project/flash-attn/
      - pyodmongo
      - realtimetts[system,coqui]
      - keyboard
      - climage
      - obsws-python
      - blizzardapi2
      - twitchAPI      
      - parametrize_from_file
      - git+https://github.com/NumberPigeon/sc2reader-plugins.git
      - git+https://github.com/StoicLoofah/spawningtool.git@master

