name: aicoach311-ci
channels:
  - conda-forge
  - simonflueckiger
dependencies:
  - python=3.11
  - pydantic=2.6
  - pydantic-settings
  - pyyaml
  - httpx
  - click
  - openai
  - pytest
  - pytest-mock
  - pytest-cov
  - python-levenshtein
  - tesserocr
  - pandas
  - tabulate
  - jinja2
  - watchdog
  - pip
  - pip:
      - opencv-python
      - sc2reader
      - spawningtool
      - pyodmongo
      - keyboard
      - blizzardapi2
      - parametrize_from_file
      - git+https://github.com/NumberPigeon/sc2reader-plugins.git
      - docker
