name: aicoach311-minimal
channels:
  - conda-forge
dependencies:
  - python=3.11
  - conda-forge::pydantic=2.6
  - conda-forge::pydantic-settings
  - pyyaml
  - pandas
  - requests
  - click
  - pymongo
  - conda-forge::openai
  - pytest
  - pytest-mock
  - pytest-cov
  - tiktoken
  - rich
  - python-levenshtein
  - blinker
  - jinja2
  - pip
  - pip:
      - sc2reader
      - spawningtool
      - pyodmongo
      - keyboard
