name: aicoach311
channels:
  - conda-forge
  - huggingface
dependencies:
  - python=3.11
  - conda-forge::pydantic=2.6
  - conda-forge::pydantic-settings
  - pyyaml
  - pandas
  - conda-forge::httpx
  - click
  - pymongo
  - numpy
  - conda-forge::openai
  - pytest
  - pytest-mock
  - pytest-cov  
  - tiktoken
  - rich
  - simonflueckiger::tesserocr
  - beautifulsoup4
  - python-levenshtein
  #- pytorch # conda install pytorch torchvision torchaudio pytorch-cuda=12.1 -c pytorch -c nvidia
  - jupyter
  - conda-forge::matplotlib
  - conda-forge::webrtcvad
  - scipy
  - jinja2
  - pillow
  - pip
  - pip:
      - pyaudio
      - pysoundfile
      - opencv-python
      - spawningtool
      - openwakeword
      - onnxruntime-gpu
      - accelerate
      - transformers
      - SpeechRecognition
      #- flash_attn # https://pypi.org/project/flash-attn/
      - pyodmongo
      - realtimetts[system,coqui]
      - keyboard
      - climage
      - obsws-python
      - blizzapi2
      - twitchAPI      
      - parametrize_from_file
      - git+https://github.com/ggtracker/sc2reader@upstream
      - # SC2 reader plugins pip install git+https://github.com/NumberPigeon/sc2reader-plugins.git

