name: aicoach
channels:
  - conda-forge
dependencies:
  - python=3.12
  - requests=2.31.0
  - python-dotenv=0.21.0
  - click=8.1.7
  - pyyaml=6.0.1
  - pymongo=4.6.1
  - numpy=1.26.2
  - pandas=2.1.4
  - openai=1.6.1
  - pytest=7.4.0
  - tiktoken=0.5.2
  - rich=13.7.0
  - pytesseract=0.3.13
  - beautifulsoup4=4.12.2
  - python-levenshtein=0.23.0
  - onnxruntime=1.17.0
  - blinker=1.7.0
  - pip
  - pip:
      - pyaudio=0.2.14
      - opencv==4.9.0
      - sc2reader==1.8.0
      - spawningtool==2.10.0
      - openwakeword==0.5.1
      - openai-whisper==20231117
