name: aicoach311-minimal
channels:
  - conda-forge
dependencies:
  - python=3.11
  - conda-forge::pydantic=2.6
  - conda-forge::pydantic-settings
  - pyyaml
  - conda-forge::httpx
  - click
  - pymongo
  - conda-forge::openai
  - tiktoken
  - rich
  - python-levenshtein
  - blinker
  - jinja2
  - pip
  - pip:
      - sc2reader
      - spawningtool
      - pyodmongo
      - keyboard
      - climage
      - blizzapi2
      - parametrize_from_file
      - git+https://github.com/NumberPigeon/sc2reader-plugins.git