name: aicoach311
channels:
  - conda-forge
  - huggingface
dependencies:
  - python=3.11
  - conda-forge::pydantic=2.6
  - conda-forge::pydantic-settings
  - requests
  - python-dotenv
  - click
  - pyyaml
  - pymongo
  - numpy
  - pandas
  - conda-forge::openai
  - pytest
  - pytest-mock
  - tiktoken
  - rich
  - pytesseract
  - beautifulsoup4
  - python-levenshtein
  - onnxruntime
  - blinker
  #- pytorch # conda install pytorch torchvision torchaudio pytorch-cuda=12.1 -c pytorch -c nvidia
  - pip
  - pip:
      - pyaudio
      - pysoundfile
      - opencv-python
      - sc2reader
      - spawningtool
      - openwakeword
      - optimum
      - accelerate
      - transformers
      - SpeechRecognition
      - pyttsx3
      - pydantic-yaml
      #- flash_attn # https://pypi.org/project/flash-attn/
      - pyodmongo
