name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: aicoach311-ci
          environment-file: environment-cp311-ci.yml
          python-version: 3.11
          auto-activate-base: false
      - name: Test with pytest
        run: |
          pytest tests/unit --doctest-modules --junitxml=tests/test-results.xml --cov=. --cov-report=xml --cov-report=html
        env:
          AICOACH_MONGO_DSN: mongodb://localhost:27017
          AICOACH_ASSISTANT_ID: "XXX"
          AICOACH_OPENAI_API_KEY: "YYY"
          AICOACH_OPENAI_ORG_ID: "ZZZ"
      - name: Surface failing tests
        if: always()
        uses: pmeier/pytest-results-action@main
        with:
          # A list of JUnit XML files, directories containing the former, and wildcard
          # patterns to process.
          # See @actions/glob for supported patterns.
          path: tests/test-results.xml

          # (Optional) Add a summary of the results at the top of the report
          summary: true

          # (Optional) Select which results should be included in the report.
          # Follows the same syntax as `pytest -r`
          display-options: fEX

          # (Optional) Fail the workflow if no JUnit XML was found.
          fail-on-empty: true

          # (Optional) Title of the test results section in the workflow summary
          title: Test results
